// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20211029182230_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnimalAge")
                        .HasColumnType("int");

                    b.Property<string>("AnimalName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AnimalType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            AnimalAge = 7,
                            AnimalName = "Robbie",
                            AnimalType = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            AnimalAge = 4,
                            AnimalName = "Debster",
                            AnimalType = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            AnimalAge = 2,
                            AnimalName = "Stibbons",
                            AnimalType = "Cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            AnimalAge = 3,
                            AnimalName = "Doug",
                            AnimalType = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            AnimalAge = 1,
                            AnimalName = "Pumpkin",
                            AnimalType = "Dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
